### ISSUE TITLE
Symbol not found on OSX

### ISSUE THREAD

**Issue by Sunify** [preillyme/v8js#141]
I build extension following [instruction](https://github.com/preillyme/v8js/blob/master/README.MacOS.md), but have error in runtime:
````
dyld: Symbol not found: __ZN2v88platform21CreateDefaultPlatformEi
  Referenced from: /usr/lib/php/extensions/no-debug-non-zts-20121212/v8js.so
  Expected in: flat namespace
````

What am i doing wrong?

**Comment by sormy** [comment]
use homebrew
```
brew tap universalsoftware/extra
brew install universalsoftware/extra/php55-v8js
or
brew install universalsoftware/extra/php56-v8js
```

**Comment by koriym** [comment]
same here.

homebrew v8js install cause error as follows.

```
$ brew install universalsoftware/extra/php55-v8js

Error: cannot load such file -- /usr/local/Library/Taps/universalsoftware/homebrew-extra/../../homebrew/homebrew-php/Abstract/abstract-php-extension
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/universalsoftware/homebrew-extra/php55-v8js.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:38:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:87:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:78:in `klass'
/usr/local/Library/Homebrew/formulary.rb:74:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:171:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:211:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:95:in `install'
/usr/local/Library/brew.rb:87:in `<main>'
```
